### PR TITLE
Update main.cpp

### PR DESCRIPTION
**Pull request by AingeruJM**
Some minor corrections in the formula

### CODE REVIEW

**Comment by jeanmatthieud** [comment]
Did you test it ?
Thx

**Comment by AingeruJM** [comment]
Yep.
It is true that the LED_min value has to be tweeked depending on battery, LED...

Also I would like to suggest a small change in the code.
Right now, when it "finishes" a cycle it stops right there, no matter LED value, I would like to suggest to make it fade slowly (so there is not a sudden switch off of the LED) finishing the current cycle. Right now I do not know how to make it

Regards,

**Comment by AingeruJM** [comment]
So?
Does it work for you?

**Comment by AingeruJM** [comment]
@jeanmatthieud , if it is ok for you too, you could amend the code.

**Pull request merged**
